spring:
  data:
    mongodb:
      uri: mongodb://{MONGODB_ENDPOINT}/{DATABASE_NAME}

  datasource:
    url: jdbc:mysql://[MYSQL_ENDPOINT}:3306/{DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: {USER_ID}
    password: {USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    properties.hibernate.enable_lazy_load_no_trans: true
    hibernate.ddl-auto: update

  jwt:
    secret: {JWT_SECRET_KEY}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: {NAVER_CLIENT_ID}
            client-secret: {NAVER_CLIENT_SECRET_KEY}
            redirect-uri: {SERVER_DOMAIN}:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
          kakao:
            client-name: kakao
            client-id: {KAKAO_CLIENT_ID}
            client-secret: {KAKAO_CLIENT_SECRET_KEY}
            redirect-uri: {SERVER_DOMAIN}:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  logging:
    level:
      com.vamos.characterlit: debug
      com.vamos.hikari.HikariConfig: DEBUG
      com.vamos.hikari: TRACE

  ssafy:
    apiKey: {SSAFY_FINANCIAL_API_KEY}
    accountKey: {SSAFY_FINANCIAL_ACCOUNT_KEY}
    mainAccount: {SSAFY_FINANCIAL_ACCOUNT_ID}
    pointKey: {SSAFY_FINANCIAL_BANK_KEY}
    pointAccount: {SSAFY_FINANCIAL_BANk_ACCOUNT_ID}
    feeKey: {SSAFY_FINANCIAL_FEE_KEY}
    feeAccount: {SSAFY_FINANCIAL_FEE_ACCOUNT_ID}
    registUserUrl: {REGIST_USER_API_URL}
    findUserUrl: {FIND_USER_API_URL}
    accountInfoUrl: {USER_INFO_API_URL}
    accountTransferUrl: {ACCOUNT_TRANSFER_API_URL}
    accountHistoryUrl: {ACCOUNT_HISTORY_API_URL}
  pay:
    cid: TC0ONETIME
    clientId: {KAKAO_PAY_CLIENT_ID}
    secretKey: {KAKAO_PAY_SECRET_KEY}
    readyUrl: {KAKAO_PAY_READY_URL}
    approveUrl: {KAKAO_PAY_APPROVE_URL}
    host: {HOST_URL}
  rabbitmq:
    host: {HOST_URL}
    port: 5672
    username: {RABBITMQ_USER_NAME}
    password: {RABBITMQ_USER_PASSWORD}
    virtual-host: /
cloud:
  aws:
    # aws 키 유출되지 않게 조심해주세요
    credentials:
      accessKey: {AWS_ACCESS_KEY}
      secretKey: {AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: {S3_BUCKET_NAME}
    thumbnail-name: {S3_BUCKET_THUMBNAIL_NAME}